### PR TITLE
mt76x2: fix fucking "use the new bitfield accessor macros" errors

### PR DESCRIPTION
**Pull request by p055877632**
[https://github.com/openwrt/mt76/issues/47](https://github.com/openwrt/mt76/issues/47)

you know "use the new bitfield accessor macros" this shit

is not Compile on openwrt

### CODE REVIEW

**Comment by nbd168** [comment]
No need to use strong language here. The correct fix is to backport the mac80211 updates from LEDE to OpenWrt.

**Comment by psyborg55** [comment]
old or new macros it doesn't matter. enough to change util.h only. and fix goddamn whitespaces

**Comment by nbd168** [comment]
I will not adjust mt76.git to be compatible with the old mac80211 package from OpenWrt. I'm working on upstreaming mt76 and adding compatibility hacks for old code makes it harder for me to keep the repository in sync with my upstream submission patches.

**Comment by nbd168** [comment]
What whitespaces need fixing?

**Comment by psyborg55** [comment]
nvm, the code he put back to util.h was damaged and refused to build unless spaces were removed.

**Pull request closed without merging**
