### PR TITLE
[mt7663] just some align changes to property drivers

### PR DESCRIPTION
**Pull request by ptpt52**

### CODE REVIEW

**Comment by ptpt52** [comment]
@ryderlee1110  
hi, man
I am not very familiar with the details of the property driver, I hope you can help me review these changes

**Comment by ryderlee1110** [comment]
any issues actually solved by these changes?

**Comment by ptpt52** [comment]
this really make the `recovery` work
on some case the muc hardware detect hang and `irq` status comes with `MCU_CMD_ERROR` event
and we should handle it and do the `reset_work`

**Comment by ptpt52** [comment]
and this make `reset_work` correctly on chip mt7663
the `MT_MCU_INT_EVENT` should be `MT7663_MCU_INT_EVENT` on chip mt7663
and the `MT_INT_MCU_CMD` should be `MCU2HOST_SW_INT_ENA`

**Comment by ptpt52** [comment]
Tested on chip mt7613 and it is likely fix the `mcu timeout` issue
with this commit "mt7615: make the reset_work work for mt7663"

**Comment by ptpt52** [comment]
close via https://github.com/openwrt/mt76/commit/42a2dddb706b47d6a6c36698aeb594bd0d20f92b

**Comment by sanitariu** [comment]
Any similar fixes for "mt76_wmac 10300000.wmac: MCU message 08 (seq 5) timed out" messages on mediatek 7628 i think it is mt7603 ?

**Pull request closed without merging**
