### PR TITLE
mt7615: update cr4 firmware to 20190415154149

### PR DESCRIPTION
**Pull request by skbeh**
mt7615_cr4.bin
20190121161307 -> 20190415154149

### CODE REVIEW

**Comment by barberio** [comment]
Currently testing this on a WAC124.

This firmware appears to have fixed issues with kmod-hsdma-mtk hanging the system after reboot. Suggests that 20190415154149 contains important DMA controller updates.

**Comment by namidairo** [comment]
Should probably loop in @ryderlee1110 for this, since the firmware binaries also live in linux-firmware.

That said, the cr4 from there is 20181207140436, so I figure it needed to be looked at anyway.

**Comment by barberio** [comment]
WAC124 tests with this firmware and kmod-hsdma-mtk enabled during some stress testing running eight instances of bonnie++ while performing bandwidth tests and large downloads. 802.11r and 802.11w are working, when this was unstable on this system under the prior firmware. Might indicate this firmware fixes #551. 

Worked fine for three days of normal operation.

Does not work: Trying to use the MT7615E as a client at the same time as being an AP, causes immediate panic. (Using the MT7603E as client and AP works.) This does appears to be a hardware limitation, and was not expected to work properly.

**Comment by ryderlee1110** [comment]
I don't mind to upgrade firmware, but AP/STA should be able to co-exist with each other. What does panic look like?

**Comment by barberio** [comment]
Unable to recreate the panic, but it appears that the MT7615E  radio shuts down on an attempt to use it as client and AP simultaneously. As I mentioned, this was not a stable configuration with this hardware in previous firmware, and I think it is a hardware limitation of the WAC124. (This has a side effect of killing dhcpmasq because it'll keep getting restarted along with the attempts to restart wireless.)

[system.log](https://github.com/openwrt/mt76/files/6958509/system.log)

Using a radio as AP and client simultaneously is a very unusual use-case, and the MT7603E radio continues being able to be used as client and AP simultaneously if needed.

**Comment by ryderlee1110** [comment]
I don't know what WAC124 is, but it's not a MT7615 issue as we have many users run both interfaces smoothly.

**Comment by barberio** [comment]
https://openwrt.org/toh/netgear/netgear_wac124

Please note, I'm not talking about running both radio interfaces. I'm talking about simultaneously running AP and Client on the same radio interface. I also suggest moving this to a new issue if you want to pursue it, since I'm not sure this is related specifically to the firmware, but is a hardware limitation on the device I am using.

**Comment by ryderlee1110** [comment]
I'm talking about simultaneously running AP and Client on the same radio interface.

**Comment by barberio** [comment]
The wac124 can be made to run in AP+Client mode on the same radio if that radio is set to legacy mode. This suggests that the AP issue is related to signalled power management issues, possibly due to the same issue with #576, and very likely unrelated to any particular hardware or firmware.

**Comment by skbeh** [comment]
Are there any plan to merge the pull request?

**Pull request closed without merging**
