### PR TITLE
mt7603: use eeprom 0x34 to get antenna number for mt7628.

### PR DESCRIPTION
**Pull request by Vonger**
MT7628 can work both in 1T1R and 2T2R mode, and that can be setup in eeprom at 0x34 address. This patch fix some devices who only have one antenna can not send data stably in 2T2R.

Signed-off-by: Qin Wei <me@vonger.cn>

### CODE REVIEW

**Comment by ajcollett** [comment]
Until this lands in master, and then hopefully in 19.x (will it get into 19.x?) is there a way to fix this in the base OpenWRT, without compiling everything from scratch, in an image built with the image builder?

I am creating images with the Image Builder, and before I go and build the whole of OpenWRT for this, I wanted to check.

**Comment by julianocss** [comment]
Hi.

I also have this doubt.

Juliano

**Comment by Vonger** [comment]
Looks like admin has write a new patch to master, you can use that one https://github.com/openwrt/mt76/commit/97e65131440ccae916e76323251b80cafdfc9006

**Comment by ajcollett** [comment]
I ran the snapshop version of Openwrt, and it seems like WiFi is now stable. Thanks!

Now I am just missing .so packages from mjpg-stream... Will keep trying!

**Pull request closed without merging**
