### PR TITLE
Avoid losing 2.4G on some Newifi D2 device.

### PR DESCRIPTION
**Pull request by matthew728960**
Avoid losing 2.4G on some Newifi D2 device.

This reverts commit f2ba65f73f384919aa7644a685c79f8ae7338032.

### CODE REVIEW

**Comment by matthew728960** [comment]
My newifi D2 doesn't find 2.4G with newer version, does when it revert to this.

**Comment by nbd168** [comment]
What mode are you using - AP or Client? Could you please share your wireless config?

**Comment by matthew728960** [comment]
> What mode are you using - AP or Client? Could you please share your wireless config?

```
root@OpenWrt:~# cat /etc/config/wireless

config wifi-device 'radio0'
        option type 'mac80211'
        option hwmode '11g'
        option path 'pci0000:00/0000:00:01.0/0000:02:00.0'
        option legacy_rates '1'
        option channel '11'
        option htmode 'HT20'
        option country 'CN'

config wifi-iface 'default_radio0'
        option device 'radio0'
        option network 'lan'
        option mode 'ap'
        option key '*****'
        option encryption 'psk2'
        option ssid 'iNet'

config wifi-device 'radio1'
        option type 'mac80211'
        option hwmode '11a'
        option path 'pci0000:00/0000:00:00.0/0000:01:00.0'
        option htmode 'VHT80'
        option legacy_rates '1'
        option channel '36'
        option country 'CN'

config wifi-iface 'default_radio1'
        option device 'radio1'
        option network 'lan'
        option mode 'ap'
        option ssid 'iNet'
        option key '*****'
        option encryption 'psk2'
```
Here is the eeprom.bin and firmware.bin file: (Factory.bin = eeprom.bin)
https://cloud.ithink.cf/index.php/s/X2MFdFmJLHWPTo8

Build Form source: 
https://github.com/coolsnowwolf/lede

**Comment by nbd168** [comment]
Pushed out a revert of the firmware update. Thanks for reporting this.

**Comment by lukasz1992** [comment]
Maybe lack of SMPS (introduced in fc31457cd99cb85c8cea9329eedc5edd80038f29) was the reason; could anybody check it?

**Pull request closed without merging**
