### PR TITLE
add VHT AMPDU size factor...

### PR DESCRIPTION
**Pull request by psyborg55**
... that should increase VHT mode throughput. density setting can be added the same way in case it improves anything.

Signed-off-by: Tomislav Požega <pozega.tomislav@gmail.com>

### CODE REVIEW

**Comment by Mushoz** [comment]
I noticed some other changes in the commit history regarding A-MPDU. Has this already been addressed or is this pull request still relevant?

**Comment by Mushoz** [comment]
@nbd168 and @psyborg55 care to have a look at my previous question? :)

**Comment by nbd168** [comment]
This change does not even compile, it sets a field that don't exist.

**Comment by psyborg55** [comment]
and a compiler tells exactly the path of a file that is missing a field, which in this case happened to be cfg80211.h inside backports dir and adding the missing field at ieee80211_sta_vht_cap structure helped me to compile the driver. i did not had an AC card to test the change though

**Comment by nbd168** [comment]
Adding a field there to make the change compile makes no sense at all, since it will then still be a no-op. You probably intended to add it to the VHT capabilities somehow, but those already have a value for it.
By the way, according to the vendor driver, IEEE80211_VHT_MAX_AMPDU_64K is the right value, this is what the code uses in the VHT capabilities right now.

**Pull request closed without merging**
