### PR TITLE
mt76x2: init: enable status led by default

### PR DESCRIPTION
**Pull request by guoxiaoqiao**
Modify in accordance with infomation on following URL, and test ok on my Phicomm PSG1208
https://github.com/openwrt/mt76/issues/54
https://github.com/openwrt/mt76/issues/55

### CODE REVIEW

**Comment by shawnhwei** [comment]
Any reason this hasn't been merged yet?

**Comment by EnergyMouse** [comment]
I think it should be two separate PR's.

**Comment by shawnhwei** [comment]
While I can understand that, kind of surprised no one commented on this since Feb. The survey noise error is a commonly reported issue, and these are just one line changes.

**Comment by camelcamro** [comment]
hmm, still not pulled :(

**Comment by guoxiaoqiao** [comment]
have separate to two PR

**Comment by yeryomin** [comment]
I think this PR should be superseded by this one  https://github.com/openwrt/mt76/pull/124

**Comment by nbd168** [comment]
mt76 now has proper mac80211 LED support for 7612 and 7603

**Pull request closed without merging**
