### PR TITLE
mt76: lock mt76_queue before access

### PR DESCRIPTION
**Pull request by ptpt52**
This may fix potential tx hang

### CODE REVIEW

**Comment by xback** [comment]
@nbd168

**Comment by nbd168** [comment]
How does it fix a potential tx hang?

**Comment by ptpt52** [comment]
no, it would never happens on this code, but it should be lock.

**Comment by nbd168** [comment]
The dma_map_single is intentionally left outside of the lock for performance reasons

**Comment by ptpt52** [comment]
> The dma_map_single is intentionally left outside of the lock for performance reasons

true
but we still have to lock before access q
maybe do some changes to this to skip the dma_map_single lock.

**Comment by ptpt52** [comment]
```
diff --git a/dma.c b/dma.c
index 6ea58aec..8d1d21cb 100644
--- a/dma.c
+++ b/dma.c
@@ -333,6 +333,11 @@ mt76_dma_tx_queue_skb_raw(struct mt76_dev *dev, struct mt76_queue *q,
        buf.len = skb->len;
 
        spin_lock_bh(&q->lock);
+       if (q->queued + 1 >= q->ndesc - 1) {
+               dma_unmap_single(dev->dev, buf.addr, buf.len, DMA_TO_DEVICE);
+               spin_unlock_bh(&q->lock);
+               return -ENOMEM;
+       }
        mt76_dma_add_buf(dev, q, &buf, 1, tx_info, skb, NULL);
        mt76_dma_kick_queue(dev, q);
        spin_unlock_bh(&q->lock);
```

what about this changes?
@nbd168

**Comment by nbdSorry** [comment]
Sorry @nbd168 for insulting you.

sorry

**Comment by Brain2000** [comment]
@ptpt52 Should it "goto error'" instead of "return -ENOMEM;", otherwise it will miss out on a dev_kfree_skb(skb);

**Comment by Brain2000** [comment]
@ptpt52 Also it now looks like dev->dev is now dev->dma_dev

**Comment by ptpt52** [comment]
I think this PR should be dropped.

**Comment by Brain2000** [comment]
> I think this PR should be dropped.

I spotted this same potential issue a week before I read this thread. Since we both noticed the same thing, I thought it might be worth a shot, and manually patched your code change into my local build.

I'm in the process of tracking down an mt76 kernel panic and to the point where I'm grasping for straws poring through the source code, making manual modifications on a weekly basis, hoping that something will work.

**Comment by ptpt52** [comment]
@Brain2000  
fine.
if you get the crash log?

**Comment by Brain2000** [comment]
Yes, that's on my todo list.
I'm hooking up the serial port this week, because the ramoops doesn't work because the Belkin RT3200 crashes in such a way that it must be fully power cycled to get it back online....

**Pull request closed without merging**
